args: !!python/object:argparse.Namespace
  accelerator: null
  accumulate_grad_batches: null
  add_noise: false
  amp_backend: native
  amp_level: null
  audio_dataset: SingleChannelAVSpeech
  audio_dataset_path: /scratch/vahid/AVSpeech/
  audio_only: true
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  batch_size: 16
  benchmark: null
  check_val_every_n_epoch: 1
  ckpt_path: last
  cond_disc: false
  default_root_dir: null
  denoise_audio: false
  detect_anomaly: false
  deterministic: null
  devices: null
  downsamp_factor: 4
  duration: 3.0
  dynamic_mixing: true
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  exp_name: melgan
  fast_dev_run: false
  gpus: null
  gradient_clip_algorithm: null
  gradient_clip_val: null
  inference_mode: true
  ipus: null
  lambda_feat: 10
  limit_predict_batches: null
  limit_test_batches: null
  limit_train_batches: null
  limit_val_batches: null
  log_every_n_steps: 50
  logger: true
  lr: 0.0001
  max_epochs: null
  max_steps: -1
  max_time: null
  mic_idx:
  - 0
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  moving_source: false
  multiple_trainloader_mode: max_size_cycle
  n_layers_D: 4
  n_mel_channels: 80
  n_residual_layers: 3
  n_speakers: 1
  ndf: 16
  ngf: 32
  noise_dataset: WHAM
  noise_dataset_path: ./
  noise_db_bounds: !!python/tuple
  - -2.5
  - 2.5
  noise_db_bounds_test: !!python/tuple
  - -2.5
  - 2.5
  num_D: 3
  num_dataset_workers: 40
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 2
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  ref_mic: 0
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  sampling_rate: 16000
  seed: 0
  seq_len: 8192
  start_from_beginning: 0
  strategy: null
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: null
